config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portfolio.urls')),
]

portfolio/urls.py
from django.urls import path
from . import views

app_name = 'portfolio'

urlpatterns = [
    path('', views.entry_page_view),
    path('index', views.entry_page_view, name='index'),
    path('home', views.home_page_view, name='home'),
    path('login-submit', views.submit_login, name='login-submit'),
    path('disciplinas', views.disciplinas_page_view, name='disciplinas'),
    path('projetos', views.projetos_page_view, name='projetos'),
    path('blog', views.blog_page_view, name='blog'),
    path('quizz', views.quizz_page_view, name='quizz'),
    path('logout', views.logout_user, name='logout'),
]

portfolio/models.py
import imp

from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class Post(models.Model):
    autor = models.CharField(max_length=100)
    data = models.DateTimeField(auto_now_add=True)
    titulo = models.CharField(max_length=100)
    descricao = models.TextField()

    def __str__(self):
        return self.titulo[:20] + '...'


class PontuacaoQuizz(models.Model):
    nome = models.CharField(unique=True, max_length=50)
    pontos = models.PositiveIntegerField()


class Cadeira(models.Model):
    nome = models.CharField(max_length=50)
    ano = models.IntegerField(validators=[MinValueValidator(1),
                                          MaxValueValidator(3)])
    semestre = models.IntegerField(validators=[MinValueValidator(1),
                                               MaxValueValidator(2)])
    ects = models.IntegerField(validators=[MinValueValidator(1),
                                           MaxValueValidator(6)])

    def __str__(self):
        return self.nome[:30] + '...'


class Projeto(models.Model):
    titulo = models.CharField(max_length=50)
    descricao = models.TextField(max_length=500)
    ano_realizacao = models.IntegerField(validators=[MinValueValidator(1),
                                                     MaxValueValidator(3)])
    cadeira = models.ForeignKey(Cadeira, on_delete=models.DO_NOTHING, blank=True, null=True)

    def __str__(self):
        return self.titulo[:50]

portfolio/forms.py
from django import forms
from django.forms import ModelForm
from .models import Post


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = '__all__'
    # inserção de classes CSS para formatação de cada campo do formulário
        widgets = {
            'titulo': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Título'}),
            'descricao': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Conteúdo'}),
        }


    # texto a exibir junto à janela de inserção
        labels = {
            'titulo': 'Título',
            'concluido': 'Concluído',
        }

portfolio/views.py
import imp
from logging.config import IDENTIFIER

from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib import messages
import datetime
from django.contrib.auth.decorators import login_required
from .models import *
from .forms import *
from matplotlib import pyplot as plt

# Create your views here.

def disciplinas_page_view(request):
    context = {'cadeiras': Cadeira.objects.all().order_by('semestre')}

    return render(request, 'portfolio/disciplinas.html', context)

def projetos_page_view(request):
    context = {'projetos': Projeto.objects.all()}

    return render(request, 'portfolio/projetos.html', context)

def entry_page_view(request):
    agora = datetime.datetime.now()
    local = 'Lisboa'
    topicos = ['HTML', 'CSS', 'Python', 'Django', 'JavaScript']

    context = {
        'hora': agora.hour,
        'minutos': agora.minute,
        'local': local,
        'topicos': topicos,
    }

    return render(request, 'portfolio/index.html', context)

def submit_login(request):
    if request.POST:
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('/home')
        else:
            messages.error(request, 'Utilizador ou senha inválida, tente novamente')
    return redirect('/')

def logout_user(request):
    logout(request)
    return redirect('/')

def home_page_view(request):
    agora = datetime.datetime.now()
    local = 'Lisboa'
    topicos = ['HTML', 'CSS', 'Python', 'Django', 'JavaScript']

    context = {
        'hora': agora.hour,
        'minutos': agora.minute,
        'local': local,
        'topicos': topicos,
    }

    return render(request, 'portfolio/home.html', context)

def blog_page_view(request):
    form = PostForm(request.POST or None)
    if form.is_valid():
        if request.user.is_authenticated:
            form.save()
            return HttpResponseRedirect(reverse('portfolio:blog'))
        else:
            messages.error(request, 'Tem de efetuar login para submeter um post.')

    context = {'form': form, 'posts': Post.objects.all().order_by('data').reverse}
    return render(request, 'portfolio/blog.html', context)

def pontuacao_quizz(request):
    pontos = 0

    if request.POST['pergunta_1'] == 'r2':
        pontos += 25
    if request.POST['pergunta_2'] == 'r3':
        pontos += 25
    if request.POST['pergunta_3'] == 'r2':
        pontos += 25
    if request.POST['pergunta_4'] == 'r3':
        pontos += 25

    return pontos

def grafico_pontuacao():
    sorted_bd = sorted(PontuacaoQuizz.objects.all(), key=lambda objecto: objecto.pontos, reverse=True)
    nomes = [objecto.nome for objecto in sorted_bd]
    pontuacoes = [objecto.pontos for objecto in sorted_bd]
    plt.barh(nomes,pontuacoes)
    plt.savefig('portfolio/static/portfolio/images/grafico_resultados.png', bbox_inches='tight')
    plt.close()

def quizz_page_view(request):
    if request.method == 'POST':
        n = request.POST['nome']
        p = pontuacao_quizz(request)
        
        PontuacaoQuizz.objects.update_or_create(nome=n, defaults={'pontos':p})

        grafico_pontuacao()

    return render(request,"portfolio/quizz.html")

portfolio/templates/portfolio/apresentacao.html
<!-- licenciatura.html -->

{% extends 'portfolio/layout.html' %}

{% block main %}
<h3>Licenciatura</h3>
<h4>Cadeiras</h4>
<div class="cadeiras">


</div>
{% endblock %}

portfolio/templates/portfolio/blog.html
<!-- blog.html -->

{% extends 'portfolio/header.html' %}
{% load static %}

{% block main %}
<div id="container-grey">
    <h2 class="slide">Blog</h2>
    <div id="blog">
    
        {% for post in posts %}
        <div class="container-post">
            <div>
                <h1>{{ post.titulo }}</h1>
            </div>
            <div>{{ post.descricao }}</div>
            <div><i>{{ post.autor }}</i> - {{ post.data }}</div>
        </div>
        {% endfor %}

    </div>
</div>

<div id="blog">
    <div class="container-post">
        <h2>Novo post</h2>
        {% for message in messages %}
                <div class="alert-box">
                    <strong>Erro!</strong> {{ message }}
                </div>
            {% endfor %}
        <form action="" method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <div class="form-group">
                <input type="submit" class="default-button" value="submeter"></input>
            </div>

        </form>

    </div>

</div>
{% block author %}
{% endblock %}

{% endblock %}

portfolio/templates/portfolio/disciplinas.html
<!-- licenciatura.html -->

{% extends 'portfolio/header.html' %}

{% block main %}
<div id="container-grey">
    <h2 class="slide">Unidades Curriculares</h2>
    <div class="fade-in">
        <div>
            <h3 class="slide">1º ano</h3>
        </div>

        <div id="container-full">
            {% for cadeira in cadeiras %}
            {% if cadeira.ano == 1 %}
            <div class="box-1">
                <div class="nome">
                    <h3>{{ cadeira.nome }}</h3>
                </div>
                <div class="info">
                    <p>{{ cadeira.ano }} ano | {{ cadeira.semestre }} semestre</p>
                    <p>{{ cadeira.ects }} ECTS</p>
                </div>
            </div>
            {% endif %}
            {% endfor %}


        </div>
        <div>
            <h3 class="slide">2º ano</h3>
        </div>

        <div id="container-full">
            {% for cadeira in cadeiras %}
            {% if cadeira.ano == 2 %}
            <div class="box-1">
                <div class="nome">
                    <h3>{{ cadeira.nome }}</h3>
                </div>
                <div class="info">
                    <p>{{ cadeira.ano }} ano | {{ cadeira.semestre }} semestre</p>
                    <p>{{ cadeira.ects }} ECTS</p>
                </div>
            </div>
            {% endif %}
            {% endfor %}

        </div>

        <div>
            <h3 class="slide">3º ano</h3>
        </div>

        <div id="container-full">
            {% for cadeira in cadeiras %}
            {% if cadeira.ano == 3 %}
            <div class="box-1">
                <div class="nome">
                    <h3>{{ cadeira.nome }}</h3>
                </div>
                <div class="info">
                    <p>{{ cadeira.ano }} ano | {{ cadeira.semestre }} semestre</p>
                    <p>{{ cadeira.ects }} ECTS</p>
                </div>
            </div>
            {% endif %}
            {% endfor %}


        </div>
    </div>
</div>
{% endblock %}

portfolio/templates/portfolio/header.html
<!-- header.html -->

{% extends 'portfolio/layout.html' %}

{% block header %}

<header>
    {% if request.user.is_authenticated %}
    <div class="login-nav">

        <p>Está autenticado como <b><u>{{ user.get_username }}</u></b> <a href="{% url 'portfolio:logout' %}">
            <button type="button" class="log-button" onclick="openLogin()">Logout</button></a></p>

    </div>
    {% else %}
    <div class="login-nav">

        <button type="button" class="log-button" onclick="openLogin()">Login</button>

    </div>
    {% endif %}
    <nav>
        <a href="{% url 'portfolio:home' %}" class="menu-desktop">home</a>
        <a href="{% url 'portfolio:disciplinas' %}" class="menu-desktop">disciplinas</a>
        <a href="{% url 'portfolio:projetos' %}" class="menu-desktop">projetos</a>
        <a href="{% url 'portfolio:blog' %}" class="menu-desktop">blog</a>
        <a href="{% url 'portfolio:quizz' %}" class="menu-desktop">quizz</a>
        <div class="button-mobile">
            <div class="menu-button" onclick="myFunction(this), openMenu()">
                <div class="bar1"></div>
                <div class="bar2"></div>
                <div class="bar3"></div>
            </div>
        </div>
    </nav>
</header>
{% if request.user.is_authenticated == False %}
<div id="login_area_2">
    <form action="login-submit" , method="POST">
        {% csrf_token %}
        <div id="login-box">
            <div>
                <label for="username">Utilizador</label>
                <span class="input"><input type="text" , id="username" name="username"></span>
            </div>
            <div>
                <label for="password">Senha</label>
                <span class="input"><input type="password" id="password" name="password"></span>
            </div>
            <div class="input">
                <button type="submit" class="default-button" onclick="openLogin()">Entrar</button>
            </div>
        </div>

    </form>
</div>
{% endif %}

<div id="menu-mobile">
    <ul>
        <li><a href="{% url 'portfolio:home' %}">home</a></li>
        <li><a href="{% url 'portfolio:disciplinas' %}">disciplinas</a></li>
        <li><a href="{% url 'portfolio:projetos' %}">projetos</a></li>
        <li><a href="{% url 'portfolio:blog' %}">blog</a></li>
        <li><a href="{% url 'portfolio:quizz' %}">quizz</a></li>
    </ul>
</div>

<script>
    function openLogin() {
        var container_login = document.getElementById("login_area_2");
        if (container_login.style.display === "block") {
            container_login.style.display = "none";
        } else {
            container_login.style.display = "block";
        }
    }

    function openMenu() {
        var container_menu = document.getElementById("menu-mobile");
        if (container_menu.style.display === "block") {
            container_menu.style.display = "none";
        } else {
            container_menu.style.display = "block";
        }
    }

    function myFunction(x) {
        x.classList.toggle("change");
    }
</script>

{% endblock %}

portfolio/templates/portfolio/home.html
<!-- home.html -->

{% extends 'portfolio/header.html' %}
{% load static %}

{% block main %}
<div id="home" class="slide">
    <div class="perfil">
        <img src="{% static 'portfolio/images/perfil_img.png' %}" class="img-fluid rounded-circle">
    </div>
    <div class="nome">
        <h3>Diogo Moreira</h3>
    </div>
    <div class="descricao">
        <p>O sucesso é feito de pequenas vitórias!</p>
    </div>
</div>

<div id="container-white">
    <h2 class="slide" style="animation-delay: 0.5s; opacity: 0;">Skills</h2>
    <div id="competencias">
        <div id="skills" class="fade-in" style="animation-delay: 1.5s;">
            <ul>
                <li>Resiliente</li>
                <li>Colaborativo</li>
                <li>Criativo</li>
                <li>Comunicativo</li>
            </ul>
        </div>
        <div id="skills" class="fade-in" style="animation-delay: 2s;">
            <div class="skill">HTML <i class="valor">80%</i></div>
            <progress class="progress" value="75" max="100"></progress>
            <div class="skill">CSS <i class="valor">75%</i></div>
            <progress class="progress" value="75" max="100"></progress>
            <div class="skill">JAVA <i class="valor">60%</i></div>
            <progress class="progress" value="60" max="100"></progress>
        </div>
    </div>
</div>
{% endblock %}

portfolio/templates/portfolio/index.html
<!-- home.html -->

<!DOCTYPE html>

<html lang="pt-pt">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Portfolio</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'portfolio/css/layout.css' %}">

</head>

<body id="fundo_entrada">
    <div id="index">
        <section id="entrada">
            <div class="titulo">
                Programação Web
            </div>
            <div class="perfil">
                <img src="{% static 'portfolio/images/perfil_img.png' %}" class="img-fluid rounded-circle">
            </div>
            <div class="buttons">
                <a href="{% url 'portfolio:home' %}">
                    <button type="button" class="default-button">Entrar</button>
                </a>
                {% if request.user.is_authenticated %}

                <a href="{% url 'portfolio:logout' %}">
                    <button type="button" class="log-button">Logout</button>
                </a>

                {% else %}

                <button onclick="openLogin()" type="button" class="log-button">Login</button>

            </div>

            <div id="login_area">
                <form action="login-submit" , method="POST">
                    {% csrf_token %}
                    <div id="login-box">
                        <div>
                            <label for="username">Utilizador</label>
                            <span class="input"><input type="text" , id="username" name="username"></span>
                        </div>
                        <div>
                            <label for="password">Senha</label>
                            <span class="input"><input type="password" id="password" name="password"></span>
                        </div>
                        <div class="input">
                            <button type="submit" class="default-button" onclick="openLogin()">Entrar</button>
                        </div>
                    </div>
            
                </form>
            </div>
            <div>
                {% for message in messages %}
                <div class="alert-box">
                    <strong>Falha no login!</strong> {{ message }}
                </div>
                {% endfor %}
            </div>

            <script>
                function openLogin() {
                    var container_login = document.getElementById("login_area");
                    if (container_login.style.display === "block") {
                        container_login.style.display = "none";
                    } else {
                        container_login.style.display = "block";
                    }
                }
            </script>

            {% endif %}

    </div>

    </section>
    </div>
    <footer>ULHT, 2022</footer>

</body>

portfolio/templates/portfolio/layout.html
<!-- layout.html -->

<!DOCTYPE html>

<html lang="pt-pt">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Portfolio</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'portfolio/css/layout.css' %}">

</head>

<body>
    {% block header %}
    {% endblock header %}

    <main>
        {% block main %}
        {% endblock main %}
    </main>

    <footer>ULHT, 2022</footer>

</body>

</html>

portfolio/templates/portfolio/projetos.html
<!-- projetos.html -->

{% extends 'portfolio/header.html' %}
{% load static %}

{% block main %}
<div id="container-grey">
    <h2 class="slide">Projetos</h2>
    <div class="fade-in">

        <div id="container-full">
            {% for projeto in projetos %}
            <div class="box-2">
                <div class="nome">
                    <h3>{{ projeto.titulo }}</h3>
                </div>
                <div class="descricao">
                    <p>Ano:{{ projeto.ano_realizacao }}</p>
                    <h4><b>Descricao:</b></h4>
                    <p>{{ projeto.descricao }}</p>

                </div>
            </div>
        </div>
        {% endfor %}

    </div>

</div>
</div>
{% endblock %}

portfolio/templates/portfolio/quizz.html
<!-- licenciatura.html -->

{% extends 'portfolio/header.html' %}
{% load static %}

{% block main %}
<div id="container-grey">
<h2 class="slide">Quizz - Programação Web</h2>
<div class="quizz">
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <fieldset id="fieldset2">
            <fieldset id="fieldset1">
                <legend>Info utilizador</legend>
                <p><input type="text" name="nome" placeholder="Nome" autocomplete="off" maxlength="50"></p>
            </fieldset>
            <fieldset id="fieldset3">
                <legend>Questões</legend>
                <div>
                    <p>Como se define uma função em Python:</p>
                    <input type="radio" id="p1_r1" name="pergunta_1" value="r1">
                    <label for="p1_r1">fun</label>
                    <br><input type="radio" id="p1_r2" name="pergunta_1" value="r2">
                    <label for="p1_r2">def</label>
                    <br><input type="radio" id="p1_r3" name="pergunta_1" value="r3">
                    <label for="p1_r3">static</label>
                </div>
                <div>
                    <p>Como se declara uma Class em CSS?</p>
                    <input type="radio" id="p2_r1" name="pergunta_2" value="r1">
                    <label for="p2_r1">#nome {}</label>
                    <br><input type="radio" id="p2_r2" name="pergunta_2" value="r2">
                    <label for="p2_r2">nome {}</label>
                    <br><input type="radio" id="p2_r3" name="pergunta_2" value="r3">
                    <label for="p2_r3">.nome {}</label>
                </div>
                <div>
                    <p>Qual a tag para definir o texto to separador numa página HTML?</p>
                    <input type="radio" id="p3_r1" name="pergunta_3" value="r1">
                    <label for="p3_r1">div</label>
                    <br><input type="radio" id="p3_r2" name="pergunta_3" value="r2">
                    <label for="p3_r2">title</label>
                    <br><input type="radio" id="p3_r3" name="pergunta_3" value="r3">
                    <label for="p3_r3">head</label>
                </div>
                <div>
                    <p>Qual a extensão de um ficheiro CSS:</p>
                    <input type="radio" id="p4_r1" name="pergunta_4" value="r1">
                    <label for="p4_r1">.html</label>
                    <br><input type="radio" id="p4_r2" name="pergunta_4" value="r2">
                    <label for="p4_r2">.js</label>
                    <br><input type="radio" id="p4_r3" name="pergunta_4" value="r3">
                    <label for="p4_r3">.css</label>
                </div>
            </fieldset>
        </fieldset>
        <input class="default-button" type="submit" value="Submeter">
    </form>
    <div id="resultados">
        <h4>Gráfico de resultados</h4>
        <img src="{% static 'portfolio/images/grafico_resultados.png' %}" alt="">
    </div>
</div>
</div>
{% endblock %}